#apiVersion: v1
#kind: Service
#metadata:
#  name: mysql
#  namespace: team-app
#spec:
#  type: ClusterIP   # Internal only
#  selector:
#    app: mysql
#  ports:
#    - name: mysql
#      port: 3306
#      targetPort: 3306
#      protocol: TCP
