apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-cicd-eks
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          image: localhost:5000/demo-app:latest
          imagePullPolicy: IfNotPresent
