apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-cicd-eks-config
  namespace: team-app
data:
  SERVER_PORT: "8080"
  DB_HOST: "mysql" # If using in-cluster MySQL service. For RDS, set to RDS endpoint.
  DB_PORT: "3306"
  DB_NAME: "appdb"
  DB_USER: "root"