#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: demo-deployment
#  namespace: team-app
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: demo-app
#  template:
#    metadata:
#      labels:
#        app: demo-app
#    spec:
#      containers:
#        - name: demo-app
#          image: localhost:5000/demo-app:latest   # ✅ local registry image
#          imagePullPolicy: IfNotPresent
#          ports:
#            - containerPort: 8080
#          env:
#            - name: SPRING_DATASOURCE_URL
#              valueFrom:
#                configMapKeyRef:
#                  name: springboot-cicd-eks-config
#                  key: DB_URL
#            - name: SPRING_DATASOURCE_USERNAME
#              valueFrom:
#                configMapKeyRef:
#                  name: springboot-cicd-eks-config
#                  key: DB_USER
#            - name: SPRING_DATASOURCE_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: springboot-cicd-eks-secret
#                  key: DB_PASSWORD
#            - name: SERVER_PORT
#              valueFrom:
#                configMapKeyRef:
#                  name: springboot-cicd-eks-config
#                  key: SERVER_PORT
