apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-cicd-eks
  namespace: team-app
spec:
  template:
    spec:
      containers:
        - name: app
          image: docker.io/<youruser>/springboot-cicd-eks:0.0.1
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
