apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-cicd-eks
  namespace: team-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-cicd-eks
  template:
    metadata:
      labels:
        app: springboot-cicd-eks
    spec:
      containers:
        - name: springboot-cicd-eks
          image: ghcr.io/yashwant-ahirwar/springboot-cicd-eks:latest   # Always deploys latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: springboot-cicd-eks-config
            - secretRef:
                name: springboot-cicd-eks-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
