name: CI
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - name: Build with Maven
        run: mvn -f app/pom.xml -B clean package -DskipTests
      - name: Build Image
        run: |
          IMAGE=ghcr.io/yashwant-ahirwar/springboot-cicd-eks:${{ github.sha }}
          docker build -t $IMAGE -f app/Dockerfile .
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Image
        run: docker push ghcr.io/yashwant-ahirwar/springboot-cicd-eks:${{ github.sha }}
      # optional: deploy dev directly from Actions (requires kubeconfig secret)
      # - name: Kubeconfig
      #   run: echo "${{ secrets.KUBECONFIG_DEV }}" > $HOME/.kube/config
      # - name: Deploy Dev
      #   run: |
      #     kubectl kustomize k8s/overlays/dev | \
      #     sed "s#dev-latest#${{ github.sha }}#g" | kubectl apply -f -